[package]
org = "ballerina"
name = "websocket"
version = "2.0.1"
authors = ["Ballerina"]
keywords = ["ws", "network", "bi-directional", "streaming", "service", "client"]
repository = "https://github.com/ballerina-platform/module-ballerina-websocket"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/websocket-native-2.0.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/http-native-2.0.1-20211110-001100-0fda3bb.jar"

[[platform.java11.dependency]]
path = "./lib/mime-native-2.0.1-20211109-232100-241f3d6.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/websocket-test-utils-2.0.1-SNAPSHOT.jar"
scope = "testOnly"
